sequenceplanner/r2r

Cargo.toml
common/Cargo.toml
msg_gen/Cargo.toml
msg_gen/build.rs
rcl/Cargo.toml
rcl/build.rs

Hi,
First, thanks, for a useful project.
Here is a rather trivial PR that bumps versions of the crates this project depends on to where they are at the moment.
Motivation: I needed to use this create as well as latest `bindgen` 0.57.0 in one of my projects.
It turned out this was was causing a create version conflict.
I though it was a good idea to bring the trunk of `r2r` to where crates it depends on are at the moment.
Tested to work as expected with Rust 1.49 and ROS2 foxy release on Ubuntu 20.04.

Bumping version of referenced creates to latest versions.

---

r2r_msg_gen/src/lib.rs

Description: The auto generated lib r2r_msg_gen assume the presence of at least 1 entry in the messages, actions or services.
If none is present it generates a file with a dangling "else" which generates a compilation error.
Removing the else altogether fixes the issue.
Test:
- cargo test
- cd r2r_msg_gen/ && cargo test
- colcon build on local package with no actions

Fix colcon build when no actions/msgs/services are present

---

src/nodes.rs

Rust 1.66 (or rather, the clippy bundled with it) adds a new clippy check called `clippy::explicit-auto-deref`. This commit fixes an instance of it in nodes.rs

Fix clippy warning in nodes.rs

---

r2r_rcl/build.rs

Fixes undeclared type `RCUTILS_LOG_SEVERITY` on foxy.

---

r2r/src/context.rs

During rcl_init, things could fail and result in
segfault.
In this patch, we check the return code of
c function calls and panic in case of error.

Add return value checking when invoking c APIs

---

r2r/examples/publishers.rs
r2r/src/msg_types.rs
r2r/src/publishers.rs
r2r/src/subscribers.rs

Add loaned message support in R2R's subscriber to
take advantage of the shared memory backend of the middleware.
- Add new constructor to `WrappedNativeMsg` which takes a already allocated pointer, and a deallocator.
- If the subscription can loan messages, construct `WrappedNativeMsg` with the loaned message pointer.
- Pass in also a closure  as the deallocator that calls the right APIs to return the loaned message to the middleware layer.
- The deallocator is called in the destructor of `WrappedNativeMsg`
- Add borrow_loaned_message API to publisher
- Add release() api to WrappedNativeMsg so a loaded message could be manually released if not published.

Add loaned message support to R2R

---

r2r/src/publishers.rs

If the middleware does not support loaned messages, the same error is logged every time a message is sent, bloating the output. With this modification, the error is logged only once.

Log loaned msg error only once

---

r2r/src/action_clients.rs
r2r/src/action_clients_untyped.rs
r2r/src/action_common.rs
r2r/src/action_servers.rs
r2r/src/msg_types.rs
r2r_msg_gen/build.rs
r2r_msg_gen/src/lib.rs

This PR adds a heuristic to the code generation that looks for constants. They are then added as associated constants to the respective message types.

Generate constants associated to the message types.

---

Cargo.toml
README.md
r2r/Cargo.toml
r2r/examples/parameters_derive.rs
r2r/src/error.rs
r2r/src/lib.rs
r2r/src/nodes.rs
r2r/src/parameters.rs
r2r_macros/Cargo.toml
r2r_macros/src/lib.rs

This is an initial attempt to create a derive macro, which would make dealing with ROS parameters easier. Currently, it works for my simple use case, but it's far from perfect and there is several TODOs and FIXMEs in the code. I'm posting it here if @m-dahl or somebody else wants to comment on it. Please, don't look at individual commits (which are a mess), just the final diff should make sense. I'll clean up the commit history before eventual merge.
How to use this feature is best visible in the `parameters_derive.rs` example.
Before merging this, I think the following should be clarified/fixed:

Macro for deriving ROS parameters code

---

r2r/src/utils.rs
r2r_common/src/lib.rs
r2r_msg_gen/build.rs
r2r_rcl/src/lib.rs
r2r_rcl/src/rcl_wrapper.h

This PR is to have r2r works under windows, this also enable using cargo-ament for building with colcon
By default once cargo-ament is installed any package containing a package.xml and Cargo.toml is considered as cargo-ament, so using the custom r2r_cargo.cmake does not work anymore

add windows support

---

r2r/examples/parameters.rs
r2r/examples/parameters_derive.rs
r2r/src/lib.rs
r2r/src/nodes.rs
r2r/src/parameters.rs
r2r_macros/src/lib.rs

With this change, adding doc comments to fields of structures used with `#[derive(RosParams)]` results in those comments to be used as parameter description.
See `r2r/examples/parameters_derive.rs` for how to use and test this feature.
The advantage of this implementation is that it should be backward compatible with all current users of r2r crate. However, it has also some disadvantages:
- There is no API for setting parameter description without using RosParams trait. Older apps should either be ported to use RosParams or they cannot benefit from this.
- The implementation could be more efficient, if the compatibility is broken. Currently, we have two HashMaps - one for ParameterValues and another for ParameterDescriptors. It might be better to change Node::params to a HashMap whose …

Support ROS parameter descriptions

---

.github/workflows/rust_and_ros2.yml
r2r_cargo.cmake
tests/Dockerfile_foxy
tests/Dockerfile_galactic
tests/build_minimal_node.bash

Action that clones https://github.com/m-dahl/r2r_minimal_node and builds the workspace using colcon.

Add CI that builds with colcon.

---

r2r/Cargo.toml
r2r/src/nodes.rs
r2r/src/publishers.rs

Feel free to remove `wait_for_inter_process_subscribers` in particular ..

Add rcl_publisher_get_subscription_count related methods

---

r2r/examples/tokio_raw_publisher.rs
r2r/src/context.rs
r2r/src/error.rs
r2r/src/lib.rs
r2r/src/nodes.rs
r2r/src/publishers.rs
r2r/tests/threads.rs
r2r/tests/tokio_test_raw.rs
r2r/tests/tokio_testing.rs

Follow up PR to #74
I was seeing some memory corruption in the tests, which seems to be due to multiple Context instances being made (e.g. a double free in rcl_node_fini + other less legible ones intermittantly). Using a singleton fixed this. (It was not exclusively happening on the raw subscriber/publisher stuff, it was a preexisting issue.)
I don't think making Context a singleton should impact anyone using this library?
I can split into 2 PR's if desired

Add raw publisher, convert Context to singleton

---

.dockerignore
r2r/src/nodes.rs
r2r/src/qos.rs
r2r/tests/tokio_testing.rs

related issue: https://github.com/sequenceplanner/r2r/issues/78

add get_publishers_info_by_topic

---

r2r/Cargo.toml
r2r/examples/sim_time_publisher.rs
r2r/examples/timer_sim_time.rs
r2r/src/clocks.rs
r2r/src/error.rs
r2r/src/lib.rs
r2r/src/nodes.rs
r2r/src/time_source.rs
r2r/src/utils.rs

The simulated time feature (enabled with the `use_sim_time` parameter) is useful when the node is run in a simulated environment, e.g., with `ros2 bag`. It allows the simulator to run slower or faster than in real time.
This implementation is based on the existing implementation in rclcpp.
- Each node has its own `RosTime` clock that is used to create timers.
- Time source is responsible for subscribing to the `/clock` topic and updating attached clocks.
- The callback of `TimeSourceSubscriber` does not use async runtime. It is run in the `handle_incoming()` method during node spinning.
- The destruction of `TimeSourceSubscriber` is done after disabling the simulated time when the next time message is received.
rclcpp implements this feature with the help of several classes which are …

Support simulated time

---

r2r_common/examples/r2r_info.rs
r2r_common/src/lib.rs

This PR adds an `r2r_info` example that prints Markdown-formatted report, which lists the environment hash, cargo prints, etc. It is added for convenience to inspect the ROS environment.

Add a `r2r_info` example to print environmental information for r2r

---

r2r/Cargo.toml
r2r/src/lib.rs
r2r/src/nodes.rs
r2r/src/parameters.rs
r2r_macros/src/lib.rs

GUI tools for working with parameters (at least Foxglove Studio, rqt and rig_reconfigure) show the parameters in the same order as returned by the ListParameters service. r2r stores the parameters in a HashMap, which iterates keys and values in arbitrary order. The result is that the GUI tools show the parameters in different order after every node invocation, which can be quite annoying.
To make the order deterministic, we change the parameter storage from HashMap to IndexMap, which iterates the map in insertion order. According to the indexmap documentation, IndexMap is a drop-in replacement of HashMap so this change should not require code changes in applications using r2r. At least r2r examples and my projects needed no changes.

Make the order of parameters deterministic

---

r2r/examples/client.rs
r2r/examples/service.rs
r2r/examples/tokio_client.rs
r2r/examples/tokio_examples.rs
r2r/examples/tokio_service.rs
r2r/examples/untyped_client.rs
r2r/src/clients.rs
r2r/src/nodes.rs
r2r/src/services.rs

I exposed an Option<QosProfile> to the user of the crate so that he/she can alter the QoS profile for the created services.

I exposed an Option<QosProfile> to the user of the crate.

---

r2r/src/subscribers.rs

See https://github.com/sequenceplanner/r2r/issues/85
This PR fixes a memory leak on the code path returning loaned messsages to the middleware.

Avoid memory leak in loaned-message return path

---

r2r/src/subscribers.rs

This fixes undefined behaviour, as the rcl_subscription_get_topic_name documentation
states that the topic is no longer valid when the subscription dies

Copy topic name before deleting subscription.

---

r2r/src/nodes.rs
r2r_rcl/src/lib.rs

This adds a few minor asserts and improvements to the RCL layer. Specifically:
1. It adds a few `null` checks in the graph introspection code. Introspection is not particularly performance-critical, I suspect that it's worthwhile to add these checks rather than risk undefined behaviour
2. It changes the data copies in the vector-copying code from `copy` to `copy_nonoverlapping`. There is no reason not to do it and it might provide a slight speedup.

Add assertions to rcl wrapper

---

r2r/examples/parameters.rs
r2r/src/error.rs
r2r/src/nodes.rs
r2r/src/parameters.rs

TLDR: If you just want to read a single ROS parameter and not receive updates for it in the future, it's now this easy:
```rust
let serial_device: String = node
.get_parameter("serial_device")
.context("Failed to get serial device name.")?; // Graceful error handling with the anyhow crate.
let baud_rate: Option<i64> = node
.get_parameter("baud_rate")
.context("Failed to get device baud rate.")?;
let baud_rate = baud_rate.unwrap_or(115200); // By fetching an optional type, we can assume a default when the value is not set.
```
I write a lot of ROS drivers. The usual way I configure the drivers is to load their settings from ROS params.
The current method to access a ROS parameter once is quite tedious and I wanted to make it easy.
The following is an explanation of my development process …

More convinent one time parameter access

---

r2r/examples/publishers.rs
r2r/src/nodes.rs
r2r/src/publishers.rs

Functions to destroy a publisher.

add destroy publisher functions

---

r2r/src/lib.rs

I'm creating a compatibility layer of multiple robotics libraries, and I found that I need to write code like this:
```rust
pub struct NodeHandler<'b>(&'b mut r2r::Node);
pub trait ParamType: Sized
where
ParameterValue: TryInto<Self, Error = WrongParameterType>,
{
fn get(node: &mut NodeHandler, key: &str) -> Result<Self> {
let result = node.0.get_parameter::<Self>(key);
match result {
Ok(val) => Ok(val),
Err(r2r::Error::ParameterWrongType {
name: _,
expected_type: _,
actual_type: "not set",
}) => Err(crate::Error::ParameterNotFound(key.to_owned())),
Err(e) => Err(e.into()),
}
}
}
impl ParamType for bool {}
impl ParamType for String {}
impl ParamType for i64 {}
impl ParamType for f64 {}
impl ParamType for Vec<bool> {}
impl ParamType for Vec<String> {}
impl ParamType for Vec<i64> {}
impl …
```

Expose WrongParameterType

---

r2r_actions/Cargo.toml
r2r_common/Cargo.toml
r2r_msg_gen/Cargo.toml
r2r_rcl/Cargo.toml

bindgen `0.63.0` didn't expand/include the following macros on some systems:
```C
// {ROS_BASE}/include/rosidl_runtime_c/rosidl_runtime_c/primitives_sequence_functions.h
...
ROSIDL_RUNTIME_C__DECLARE_PRIMITIVE_SEQUENCE_FUNCTIONS(float)
ROSIDL_RUNTIME_C__DECLARE_PRIMITIVE_SEQUENCE_FUNCTIONS(double)
ROSIDL_RUNTIME_C__DECLARE_PRIMITIVE_SEQUENCE_FUNCTIONS(long_double)
...
```
This change fixes this by now generating the missing primitive sequence functions. 
I have manually tested it to compile and work on Ubuntu 22.04 with ROS2 Humble and Iron using some simple messages.

Update bindgen 0.63.0 -> 0.71.1 (#116)

---

r2r/src/nodes.rs
r2r/src/parameters.rs
r2r_macros/src/lib.rs

Let's fix the behavior according to spec before we merge into main. Making a PR instead of issue so it happens sooner :)
TODO.

Fix atomic behaviour for `set_parameters_atomically`
